app:
  name: dockerfile-builder
  verbose: false
  debug: false
logger:
  hooks:
    - stacktrace
aws:
  access_key_id: ==AES32==+NPjNiwCtTNvMUg94O/PVGOPc1N6ExBx7Lyz3TGRuIqVfqFoYuRNEl1gkZw=
  secret_access_key: ==AES32==onXRqpVtlebXW+dN5atvjpZGuyNH8pzkAD7tx7diCj9rnByX9+BxlESV1ehoo7D7BtoDCDf73uLYVqXDQvdOq5JoL9AAFdIr
  region: us-east-1
  sts_account: 122130270846
  sts_role: rai
  sts_role_duration_seconds: 15m
store:
  provider: s3
  base_url: http://s3.amazonaws.com
  acl: public-read
client:
  name: rai
  upload_bucket: files.rai-project.com
  bucket: userdata
  build_file: rai_build
dockerbuilder:
  broker_queue_name: rai_ppc64le_test
pubsub:
  endpoints:
    - pubsub.rai-project.com:6379
  password: ==AES32==SnY+X9yvTpvVRWo+hqq1Bjup8vvYEtDURcsO2w==
