
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Unknwon/com"
  version = "1.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.35"

[[constraint]]
  version = "~1.1.0"
  name = "github.com/davecgh/go-spew"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  version = "~1.7.0"
  name = "github.com/fatih/color"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  version = "~0.6.3"
  name = "github.com/improbable-eng/grpc-web"

[[constraint]]
  name = "github.com/k0kubun/pp"
  version = "^3.0.1"

[[override]]
  version = "^3.0"
  name = "github.com/labstack/echo"

[[constraint]]
  name = "github.com/labstack/gommon"
  version = "0.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/aws"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/broker"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/config"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/logger"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/model"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/pubsub"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/serializer"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/store"


[[constraint]]
  branch = "master"
  name = "github.com/rai-project/vipertags"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.16.0"

[[override]]
  branch = "master"
  name = "gopkg.in/mattn/go-isatty.v0"
